### ISSUE TITLE
Install within `conda` environment

### ISSUE THREAD

**Issue by abearab** [noamteyssier/sgcount#50]
I tried installing rust and cargo through `conda` and then I saw [this stackoverflow](https://stackoverflow.com/a/64328675) helpful. So, I ended up creating a conda environment with this code
```bash
conda create -n sgcount -c conda-forge rust sysroot_linux-64
```
and then I followed your installation through cargo. Although, there is this warning for me
```warning
warning: be sure to add `~/.cargo/bin` to your PATH to be able to run the installed binaries
```
I don't think this is an issue, but this might be an improvement for future users.

___
https://ostechnix.com/create-rust-virtual-environments-using-conda-in-linux/

**Comment by noamteyssier** [comment]
I didn't really envision cargo being installed through conda - maybe I should write up an installation procedure for users who haven't worked with rust in the past. 

Ideally you should just install cargo separately using [rustup](https://rustup.rs/) (not using conda) because cargo is itself a package manager to handle dependencies and whatnot. 

I'll write up a section in the readme for this
